name: Label Commenter

on:
    issues:
        types:
            - labeled
            - unlabeled
    pull_request_target:
        types:
            - labeled
            - unlabeled

jobs:
    comment:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
              with:
                  config_file: ../label-commenter-config.yml
                  ref: label_commenter # Default branch here
                  repo-token: ${{ secrets.GITHUB_TOKEN }}
            - name: Label Commenter
              uses: peaceiris/actions-label-commenter@v1
